### ISSUE TITLE
Change Component Table legend so "In Progress" becomes "Untested"

### ISSUE THREAD

**Issue by bladernr** [canonical-web-and-design/certification.ubuntu.com#34]
https://certification.ubuntu.com/components/hardware/201605-22234/

The legend at the bottom of the component tables says the following:
✔ Supported
X Unsupported
? In progress
(1) Third party driver may be required.

The "?" item should be changed to "Untested"

**Comment by nottrobin** [comment]
Thanks @bladernr. Since this is a request to change the content of the existing live site, we won't do it just yet - our goal at the moment is to replicate the site as-is. We can instead include this update in the upcoming redesign work (at which point certification.ubuntu.com will also move to ubuntu.com/certification).

**Comment by nottrobin** [comment]
I'm creating a "Redesign" label to flag issues as ones to be addressed when the redesign happens. cc. @pmahnke.
