### ISSUE TITLE
Component page linked from model page often hides the relevant manufacturer

### ISSUE THREAD

**Issue by bladernr** [canonical-web-and-design/certification.ubuntu.com#50]
https://certification.ubuntu.com/hardware/201711-25981/

On that page, we see several links in the Hardware Summary and Hardware Details that are clickthrough, presumably for more information.

Processor	
Intel Intel(R) Xeon(R) Platinum 8164 CPU @ 2.00GHz
Video	
Matrox Electronics Systems Ltd. MGA G200e [Pilot] ServerEngines (SEP1)
Ethernet	
Intel Ethernet Connection X722 for 1GbE Intel Ethernet Connection X722 for 1GbE

That last one, for example, produces this link:
https://certification.ubuntu.com/catalog/component/pci/17aa%3A4020/8086%3A37d1/

The problem is that I just clicked through from a Lenovo entry, because I'm interested in Lenovo hardware, but the resuts of that clickthrough bury the relevate Lenovo links under 45 unrelated vendors (HP, Huawei, and Fujitsu).

So AIUI, this should ONLY return Lenovo listings, or if it MUST include all, then ordering should be done so Lenovo appears first and all others appear afterwards, and likewise, if I click through from a Huawei entry, Huawei would appear first and all others afterwards.

**Comment by bladernr** [comment]
Additionally further down that list is this entry for the RAID device: 
	
LSI Logic / Symbios Logic MegaRAID SAS-3 3108 [Invader] ThinkSystem RAID 730-8i 1GB Cache PCIe 12Gb Adapter

which very clearly says this is an LSI based Lenovo ThinkSystem RAID 730-81 controller. However, when I click through:
https://certification.ubuntu.com/catalog/component/pci/1d49%3A0600/1000%3A005d/

I find that the Lenovo listings are buried under 174 results from other vendors, with the first Lenovo instance appearing at the bottom of page 7:
https://certification.ubuntu.com/catalog/component/pci/1d49%3A0600/1000%3A005d/?&page=7

(there are two very old IBM listings on Page 6 that are now technically owned by Lenovo, but those listings only exist because the 14.04 certs are still live due to ESM).

**Comment by matthewpaulthomas** [comment]
Code-wise, this would be fairly simple to implement. Each system page, instead of linking to `ubuntu.com/certification/component/{id}` for each component, would link to `ubuntu.com/certification/component/{id}?vendor={name}`. The component page would then list only those systems made by the specified vendor.

However, as far as search engines are concerned, instead of having one page per component, we’d now have one page per component × vendor that uses that component. Perhaps @caldav can correct me if I’m wrong, but I think this could hurt our SEO — because search engines would see that we now had hundreds of clusters of pages with 70%~80% [duplicate content](https://moz.com/learn/SEO/duplicate-content).

We could solve this on each variant page with `<link rel="canonical"  href="/certification/component/{id}">`, which would be deferring to a version of the page that lists all systems, regardless of vendor. But that would mean the canonical version of each component page would be a version that we weren’t actually linking to from anywhere.

So, what’s motivating this request? Have we had specific feedback from OEMs that they don’t like this aspect of component pages?
