### ISSUE TITLE
Design for {category}/models landing pages

### ISSUE THREAD

**Issue by codersquid** [canonical-web-and-design/certification.ubuntu.com#86]
We've got a comment via email about one of the iot devices being classified as Ubuntu Core when it has a classic image.

I made a PR #85 to remove the category from the list of models for the iot page. (If I do that, I actually think it makes sense to remove it from all but the server/model landing pages, but I want to ask bladernr before doing that.)

The goal would be to make display IoT devices with classic images less confusing and to remove redundant information. i.e. if everything is Server SoC on the Server SoC landing page, why bother showing that?

Ultimately we could use form factor rather than the category. Something might still say Server SoC but if there is more specific information about the form factor, it would show that instead, like we do on the details pages.

This is something to talk about with a redesign. Once the discussion happens we can talk about related API changes.

**Comment by matthewpaulthomas** [comment]
@codersquid Hi, I’m starting work on the redesign of the site. I’ve read the linked PR, and the diff, but I don’t understand the issue here.

> The goal would be to make display IoT devices with classic images less confusing and to remove redundant information. i.e. if everything is Server SoC on the Server SoC landing page, why bother showing that?

As I understand it, that’s what you removed in #85.

> Ultimately we could use form factor rather than the category. Something might still say Server SoC but if there is more specific information about the form factor, it would show that instead, like we do on the details pages.

Can you give an example or two? I don’t see anything I would understand as “form factor” on SoC pages. Thanks.

**Comment by codersquid** [comment]
Form factor information is returned in the api and used to populate the text on the hardware page.

Take this page, for example. https://certification.ubuntu.com/hardware/201710-25838

The "server soc" text comes from the api's response. Sometimes form factors might be more specific.

I just checked and form factor is already being used when it is available. It looks like I made the changes but never closed this.

**Comment by matthewpaulthomas** [comment]
Ok, I understand this issue is fixed. I’ve added [a reminder](https://docs.google.com/document/d/1vIf1vC1mg72JbzmahrcKCaRZN-qMLCgin_i9iqjUxpM/edit#heading=h.6fe5h3z4d7yv) to replicate the behaviour in the new sub-site.

I do notice another interesting issue looking at your example. The Cavium Thunder X2 CN99XX has two entries in the database, [as “Server”](https://certification.ubuntu.com/hardware/201807-26334) and [as “Server SoC”](https://certification.ubuntu.com/hardware/201710-25838), identical except for their titles, because Server and SoC are treated as separate categories when really they overlap (and both hierarchy navigation links go to /desktop).

Similarly, most of [the Raspberry Pi models listed](https://certification.ubuntu.com/iot/models?category=Ubuntu%20Core&vendors=Raspberry%20Pi%20Foundation) are listed twice, because Ubuntu Classic and Ubuntu Core are treated as non-overlapping subcategories of “IoT”, though really they do overlap (and the URLs and hierarchy navigation refer to both as “Ubuntu Core”).

The second example is confusing in search results right now, and the first example will become confusing if we stop requiring people to specify a form factor before they do a search (presenting results from multiple form factors together). If we avoid this duplication in future, one detail will be that we no longer represent model pages as being “inside” one particular category.

**Comment by matthewpaulthomas** [comment]
> I’ve added a reminder to replicate the behaviour in the new sub-site.

This is now [reflected in the new design](https://docs.google.com/document/d/1vIf1vC1mg72JbzmahrcKCaRZN-qMLCgin_i9iqjUxpM/edit#heading=h.b8dj4no3wfn3):
> Search results … should consist of:
> - a link to the model or component…
> - muted text of the form “Desktop”, “Laptop”, “Server”, “IoT”, “SoC”, or “{category} component” (**except on [form-factor pages](https://docs.google.com/document/d/1vIf1vC1mg72JbzmahrcKCaRZN-qMLCgin_i9iqjUxpM/edit#heading=h.7uwmfssyaxbl)**).

> The Cavium Thunder X2 CN99XX has two entries in the database

As you explained in our call yesterday, this is a data entry glitch rather than something that needs to be catered for in the design.
